import type { HealthCheckResult } from "@/types/health";

export function getDemoResult(): HealthCheckResult & {
  boardNames: string[];
  totalBoardsInAccount: number;
} {
  return {
    score: 62,
    scannedAt: new Date().toISOString(),
    boardsScanned: 3,
    totalItems: 187,
    summary: {
      critical: 2,
      warning: 4,
      info: 3,
    },
    boardNames: ["ניהול משימות צוות", "מעקב לקוחות", "פרויקטים 2026"],
    totalBoardsInAccount: 8,
    findings: [
      {
        id: "demo-1",
        category: "permissions",
        severity: "critical",
        title: "42 משימות בלי אחראי",
        description: "42 פריטים בבורד ״ניהול משימות צוות״ לא משויכים לאף אדם.",
        boardId: "demo-board-1",
        boardName: "ניהול משימות צוות",
        affectedItems: 42,
        suggestion: "הקצו אחראי לכל משימה פתוחה.",
        summary: "כמעט מחצית מהמשימות בבורד לא משויכות לאף אחד. משימות בלי אחראי נוטות להיתקע.",
        whyItMatters: "כשאין אחראי, אף אחד לא מרגיש אחריות — והמשימה לא זזה. זה גורם לפיגור מצטבר.",
        recommendedAction: "עברו על 42 המשימות הלא משויכות והקצו אחראי לכל אחת. התחילו מהדחופות.",
        confidence: "high",
        canBeFixedAutomatically: true,
      },
      {
        id: "demo-2",
        category: "workflow",
        severity: "critical",
        title: "18 משימות באיחור של יותר מ-14 יום",
        description: "18 פריטים עם תאריך יעד שעבר לפני יותר משבועיים.",
        boardId: "demo-board-3",
        boardName: "פרויקטים 2026",
        affectedItems: 18,
        suggestion: "בדקו אם המשימות עדיין רלוונטיות ועדכנו תאריכי יעד.",
        summary: "18 משימות שהתאריך שלהן עבר מזמן — חלקן אולי כבר לא רלוונטיות.",
        whyItMatters: "משימות באיחור משמעותי יוצרות רעש בבורד ומקשות על ניהול תעדוף.",
        recommendedAction: "עברו על 18 המשימות: סגרו מה שלא רלוונטי, עדכנו תאריכים למה שכן.",
        confidence: "high",
        canBeFixedAutomatically: false,
      },
      {
        id: "demo-3",
        category: "workflow",
        severity: "warning",
        title: "12 פריטים תקועים על ״בעבודה״ יותר מ-30 יום",
        description: "12 פריטים בסטטוס ״בעבודה״ במשך חודש ומעלה בלי שינוי.",
        boardId: "demo-board-1",
        boardName: "ניהול משימות צוות",
        affectedItems: 12,
        suggestion: "בדקו אם הפריטים האלה באמת בתהליך או שהם תקועים.",
        summary: "פריטים שנמצאים ״בעבודה״ חודש שלם ללא שינוי — ייתכן שהם שכוחים.",
        whyItMatters: "סטטוסים תקועים מעוותים את התמונה האמיתית של ההתקדמות בפרויקט.",
        recommendedAction: "בדקו כל פריט: עדכנו סטטוס, הוסיפו הערה, או העבירו ל״ממתין״.",
        confidence: "medium",
        canBeFixedAutomatically: false,
      },
      {
        id: "demo-4",
        category: "data",
        severity: "warning",
        title: "עמודת ״תקציב״ ריקה ב-78% מהפריטים",
        description: "בבורד ״פרויקטים 2026״, עמודת התקציב ריקה ב-25 מתוך 32 פריטים.",
        boardId: "demo-board-3",
        boardName: "פרויקטים 2026",
        affectedItems: 25,
        suggestion: "מלאו את עמודת התקציב או הסירו אותה אם היא לא רלוונטית.",
        summary: "עמודה שכמעט לא משתמשים בה — או שהיא מיותרת, או שחסר מידע קריטי.",
        whyItMatters: "עמודות ריקות מקשות על הפקת דוחות ומונעות מהמנהל לראות את התמונה המלאה.",
        recommendedAction: "החליטו: אם התקציב חשוב — מלאו אותו. אם לא — הסתירו את העמודה.",
        confidence: "high",
        canBeFixedAutomatically: false,
      },
      {
        id: "demo-5",
        category: "structure",
        severity: "warning",
        title: "בורד ״מעקב לקוחות״ חסרות בו עמודות ניהוליות",
        description: "לבורד חסרות עמודות סטטוס ותאריך — קשה לנהל תהליך בלעדיהן.",
        boardId: "demo-board-2",
        boardName: "מעקב לקוחות",
        affectedItems: 67,
        suggestion: "הוסיפו עמודת סטטוס ועמודת תאריך יעד לבורד.",
        summary: "בורד עם 67 פריטים בלי עמודות ניהול בסיסיות — קשה לדעת מה קורה שם.",
        whyItMatters: "בלי סטטוס ותאריך, אי אפשר לעקוב אחרי התקדמות או לזהות פיגורים.",
        recommendedAction: "הוסיפו עמודת Status ועמודת Date לבורד. זה ייקח דקה אחת ויעשה סדר.",
        confidence: "high",
        canBeFixedAutomatically: true,
      },
      {
        id: "demo-6",
        category: "permissions",
        severity: "warning",
        title: "15 פריטים בלי אחראי בבורד ״מעקב לקוחות״",
        description: "15 רשומות לקוח לא משויכות לאף איש קשר או אחראי.",
        boardId: "demo-board-2",
        boardName: "מעקב לקוחות",
        affectedItems: 15,
        suggestion: "שייכו אחראי לכל לקוח פעיל.",
        summary: "לקוחות ללא אחראי מוגדר — אף אחד לא יודע מי מטפל בהם.",
        whyItMatters: "לקוח בלי אחראי עלול ליפול בין הכיסאות ולגרום לאובדן הזדמנות.",
        recommendedAction: "עברו על 15 הלקוחות ושייכו אחראי לכל אחד.",
        confidence: "medium",
        canBeFixedAutomatically: true,
      },
      {
        id: "demo-7",
        category: "structure",
        severity: "info",
        title: "שם בורד לא ברור: ״בורד 3״",
        description: "אחד הבורדים נקרא ״בורד 3״ — שם שלא אומר כלום.",
        boardId: "demo-board-3",
        boardName: "פרויקטים 2026",
        suggestion: "שנו את שם הבורד לשם שמתאר את התוכן, למשל ״פרויקטים 2026״.",
        summary: "שמות בורדים לא ברורים מקשים על ניווט ומפחיתים שימוש.",
        confidence: "low",
        canBeFixedAutomatically: true,
      },
      {
        id: "demo-8",
        category: "data",
        severity: "info",
        title: "בורד ״ניהול משימות צוות״ — 3 פריטים ריקים לגמרי",
        description: "3 שורות בבורד שבהן רק השם מלא, כל שאר העמודות ריקות.",
        boardId: "demo-board-1",
        boardName: "ניהול משימות צוות",
        affectedItems: 3,
        suggestion: "מלאו את הפריטים או מחקו שורות ריקות.",
        summary: "שורות ריקות יוצרות רעש ומקשות על חישוב סטטיסטיקות.",
        confidence: "medium",
        canBeFixedAutomatically: false,
      },
      {
        id: "demo-9",
        category: "data",
        severity: "info",
        title: "5 עמודות לא בשימוש בבורד ״מעקב לקוחות״",
        description: "5 עמודות בבורד שריקות לחלוטין — כנראה נוצרו ולא מולאו מעולם.",
        boardId: "demo-board-2",
        boardName: "מעקב לקוחות",
        affectedItems: 5,
        suggestion: "הסתירו או מחקו עמודות שלא בשימוש כדי לנקות את הבורד.",
        summary: "עמודות ריקות לגמרי מסרבלות את הבורד ומבלבלות משתמשים חדשים.",
        confidence: "high",
        canBeFixedAutomatically: true,
      },
    ],
  };
}
